# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [46]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [47]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor, random_tensor.shape

(tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
         [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
         [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
         [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
         [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
         [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
         [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [48]:
# Create another random tensor
random_tensor_2 = torch.rand(1, 7)

# Perform matrix multiplication 
print(random_tensor.shape , random_tensor_2.shape , random_tensor_2.T.shape)
torch.matmul(random_tensor, random_tensor_2.T)


torch.Size([7, 7]) torch.Size([1, 7]) torch.Size([7, 1])


tensor([[1.6914],
        [1.7581],
        [2.0906],
        [1.8975],
        [1.7585],
        [1.7961],
        [1.8900]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [49]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor = torch.rand(7, 7)
random_tensor_2 = torch.rand(1, 7)

# Matrix multiply tensors
torch.matmul(random_tensor, random_tensor_2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [50]:
# Set random seed on the GPU
torch.cuda.manual_seed(0)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [51]:
# Set random seed
torch.manual_seed(1234)
tensor_x = torch.rand(2, 3)
tensor_y = torch.rand(2, 3)

# Check for access to GPU
print("Cuda is aviable: ", torch.cuda.is_available())

# Create two random tensors on GPU
if torch.cuda.is_available():
   tensor_x = tensor_x.to("cuda")
   tensor_y = tensor_y.to("cuda")
   
tensor_x, tensor_y

Cuda is aviable:  True


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [52]:
# Perform matmul on tensor_A and tensor_B
print(tensor_x.shape, tensor_y.shape)
result = torch.matmul(tensor_x, tensor_y.T)
result, result.shape


torch.Size([2, 3]) torch.Size([2, 3])


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [53]:
# Find max
print(result.max())
# Find min
print(result.min())


tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [54]:
# Find arg max
print(result.argmax())

# Find arg min
print(result.argmin())

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [55]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
