In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [1]:
#  checking if gpu acceleration works
!nvidia-smi

Tue Oct 15 10:40:59 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.02              Driver Version: 560.94         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3080 Ti     On  |   00000000:01:00.0  On |                  N/A |
| 47%   31C    P8             28W /  350W |     526MiB /  12288MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
### introduction to Tensors

# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
#  checking the dimensions number of a scalar
scalar.ndim

0

In [6]:
# Get tensor back as Python item
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
#  checking the dimensions number
vector.ndim

1

In [9]:
# Get tensor back as Python item, ->tensor with 2 elements cannot be converted to scalar
# vector.item() -->gives an error

In [10]:
# shape is diffrent than dimensions
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

Random Tensors:

Random tensors are important because the way many neural networks lear is that
they styart with tensor full of random numbers and then adjust those random numbers
to better represent the data. 

In [17]:
random_tensor = torch.rand(3,5)
random_tensor

tensor([[0.3268, 0.1921, 0.8592, 0.3402, 0.2386],
        [0.4119, 0.8233, 0.3271, 0.9993, 0.3391],
        [0.0251, 0.2895, 0.0277, 0.4045, 0.9290]])

In [18]:
random_tensor.ndim

2

In [19]:
random_tensor.shape

torch.Size([3, 5])

Zeros and ones tensors

In [20]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
# torch.range(0, 10) - deprecated
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes, one of 3 big errors you encounter in PyTorch & deep learning:
1. Tensor not right datatype
2. Tensor not right shape
3. Tensors not right device


In [25]:
float_32_tensor = torch.tensor([3.0, 4.0, 6.0], 
                               dtype=None,              # What datatype is the tensor
                               device=None,             # What device is your tensor on (cpu or cuda)
                               requires_grad=False)     # Tracking gradients with this tensor operations
print(float_32_tensor, f"datatype={float_32_tensor.dtype}")

tensor([3., 4., 6.]) datatype=torch.float32


In [26]:
# changing tensor datatype
new_tensor = float_32_tensor.type(torch.float16)
print(new_tensor)

tensor([3., 4., 6.], dtype=torch.float16)


Getting information from tensor:
1. tensor.dtype - getting datatype
2. tensor.shape - getting tensors shape
3. tensor.device - getting the device the tensor is running on

In [27]:
some_tensor = torch.rand(3, 4)
print(f"""  
tensor datatype: {some_tensor.dtype},
tensor shape: {some_tensor.shape},
tensor device: {some_tensor.device}
""")

  
tensor datatype: torch.float32,
tensor shape: torch.Size([3, 4]),
tensor device: cpu



## Tensor operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication


In [28]:
tensor = torch.tensor([1, 2, 3])


In [29]:
tensor + 10

tensor([11, 12, 13])

In [30]:
tensor * 10

tensor([10, 20, 30])

In [31]:
tensor - 10

tensor([-9, -8, -7])

In [32]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [33]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [34]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [35]:
torch.divide(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

In [36]:
torch.subtract(tensor, 10)

tensor([-9, -8, -7])

## Matrix multiplication

In [37]:
X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"X = {X}\n")
print(f"X * X = {X*X}\n")
print(f"Matrix multiplication:\n torch.matmul(X, X) = {torch.matmul(X, X)}")

X = tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

X * X = tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

Matrix multiplication:
 torch.matmul(X, X) = tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])


In [38]:
%%time
# how to get cpu time
torch.matmul(X, X)

CPU times: user 159 μs, sys: 7 μs, total: 166 μs
Wall time: 124 μs


tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

One of the most common errors in deep learning is shape errors.

1. The inner dimensions of tensors must mach
- '(3, 2) @ (3, 2)' won't work
- '(2, 3) @ (3, 2)' will work
- '(3, 2) @ (2, 3)' will work

2. The resulting matrix has the shape of outer dimensions
- '(2, 3) @ (3, 2)' -> '(2, 2)'
- '(3, 2) @ (2, 3)' -> '(3, 3)'

In [39]:
# '(3, 2) @ (3, 2)' won't work
X = torch.rand(3, 2)
Y = torch.rand(3, 2)
# torch.matmul(X, Y) # RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [40]:
# '(3, 2) @ (2, 3)' won't work
X = torch.rand(3, 2)
Y = torch.rand(2, 3)
torch.matmul(X, Y) # works fine

tensor([[1.0979, 1.1549, 0.9640],
        [0.4420, 0.4433, 0.2709],
        [1.2029, 1.2603, 1.0288]])

In [41]:
# '(3, 2) @ (2, 3)' won't work
X = torch.rand(2, 3)
Y = torch.rand(3, 2)
torch.matmul(X, Y) # works fine

tensor([[1.7938, 0.9720],
        [1.3248, 1.1904]])

Transposition can be used like shown below:

In [42]:
X = torch.rand(2, 3)
Y = torch.rand(2, 3)
torch.matmul(X, Y.T)


tensor([[0.9630, 1.1275],
        [0.5173, 0.7221]])

## MIN, MAX, MEAN, SUM:

In [43]:
TENSOR = torch.rand(3, 5)
TENSOR

tensor([[0.5030, 0.1451, 0.1400, 0.1288, 0.9200],
        [0.5027, 0.0220, 0.8171, 0.9499, 0.1266],
        [0.9426, 0.1065, 0.6636, 0.2829, 0.5365]])

In [44]:
print(f"""minimum: {TENSOR.min(), torch.min(TENSOR)}
maximum: {TENSOR.max(), torch.max(TENSOR)}
mean: {TENSOR.mean(), torch.mean(TENSOR)}
sum: {TENSOR.sum(), torch.sum(TENSOR)}
""")

minimum: (tensor(0.0220), tensor(0.0220))
maximum: (tensor(0.9499), tensor(0.9499))
mean: (tensor(0.4525), tensor(0.4525))
sum: (tensor(6.7873), tensor(6.7873))



In [45]:
print(f"index of min = {TENSOR.argmin()}")
print(f"index of max = {TENSOR.argmax()}")

index of min = 6
index of max = 8


## Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshape an input tensor to a defined shape
* View - Return a view of an input tensor of as certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (horizontal and vertical stack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [46]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

1. Reshaping
* total number of elements must match

In [47]:
# x_reshaped = x.reshape(1, 7) # RuntimeError: shape '[1, 7]' is invalid for input of size 9
# x_reshaped = x.reshape(2, 9) # RuntimeError: shape '[2, 9]' is invalid for input of size 9
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [48]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [49]:
y = torch.rand(6)
y, y.shape

(tensor([0.9519, 0.8204, 0.9867, 0.4527, 0.6964, 0.5625]), torch.Size([6]))

2. View
* Works like reshape, but output shares memory with the input, changing one affects the other

In [50]:
z = y.view(2, 3)
z[0][0] = 0.0
print(f"y and its shape: {y, y.shape}")
print(f"z and its shape: {z, z.shape}")

y and its shape: (tensor([0.0000, 0.8204, 0.9867, 0.4527, 0.6964, 0.5625]), torch.Size([6]))
z and its shape: (tensor([[0.0000, 0.8204, 0.9867],
        [0.4527, 0.6964, 0.5625]]), torch.Size([2, 3]))


3. Stack
* stasks the tensor along one of its dimensions, cannot use higher dimensions than what tensor has

In [51]:
x_stacked = torch.stack([x, x, x, x, x], dim=0)
x_stacked, x.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([9]))

In [52]:
x_stacked = torch.stack([x, x, x, x, x], dim=1)
x_stacked, x.shape

(tensor([[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4.],
         [5., 5., 5., 5., 5.],
         [6., 6., 6., 6., 6.],
         [7., 7., 7., 7., 7.],
         [8., 8., 8., 8., 8.],
         [9., 9., 9., 9., 9.]]),
 torch.Size([9]))

4. Squeeze

In [53]:
x = torch.zeros(1, 2, 2, 1, 2)
x, x.shape

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]],
 
 
          [[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([1, 2, 2, 1, 2]))

In [54]:
x = x.squeeze()     # or torch.squeeze(x)
x, x.shape

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

5. Unsqueeze

In [55]:
x = x.unsqueeze(dim=0)
x, x.shape

(tensor([[[[0., 0.],
           [0., 0.]],
 
          [[0., 0.],
           [0., 0.]]]]),
 torch.Size([1, 2, 2, 2]))

In [56]:
x = x.unsqueeze(dim=-2)
x, x.shape

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]],
 
 
          [[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([1, 2, 2, 1, 2]))

6. Permute - rearanges the dimensions of a target tensor in a specific order
* Input and output share memory like in view !

In [57]:
# example image tensor
IMAGE = torch.rand(480, 640, 3)
IMAGE.shape

torch.Size([480, 640, 3])

In [58]:
IMAGE_PERMUTED = IMAGE.permute(2, 0, 1)
IMAGE_PERMUTED.shape

torch.Size([3, 480, 640])

In [59]:
IMAGE_PERMUTED[0][0][0] = 1.0
IMAGE[0][0][0]

tensor(1.)

In [60]:
IMAGE_PERMUTED[2][479][639] = 1.0
IMAGE[479][639][2]

tensor(1.)

In [61]:
print(IMAGE_PERMUTED[0][:][1])

tensor([1.0591e-01, 3.9826e-01, 4.2448e-01, 6.1355e-01, 8.1116e-02, 4.2014e-01,
        5.8168e-01, 6.7445e-01, 8.3217e-01, 6.2294e-01, 6.3529e-01, 6.5074e-01,
        7.8430e-01, 7.6170e-01, 4.7273e-01, 9.5904e-01, 3.0480e-01, 8.0973e-01,
        1.9627e-01, 3.8789e-01, 3.7401e-01, 1.4615e-01, 5.0834e-01, 7.4194e-01,
        6.4262e-01, 8.5811e-01, 5.2456e-01, 2.4709e-01, 6.6109e-01, 4.5582e-01,
        6.6452e-01, 3.7271e-01, 6.9997e-01, 3.7955e-01, 4.7598e-01, 1.0049e-01,
        3.5870e-01, 2.1851e-01, 4.4021e-01, 4.4045e-01, 6.2671e-01, 3.0792e-01,
        8.9905e-01, 9.9817e-01, 8.8192e-01, 7.3421e-01, 8.2625e-01, 5.9338e-01,
        9.7260e-01, 8.8012e-01, 6.2395e-01, 4.9621e-01, 5.9999e-01, 5.8098e-01,
        5.2860e-01, 4.9689e-01, 2.2042e-01, 6.7091e-01, 2.1239e-01, 2.6579e-01,
        7.3606e-01, 3.6749e-01, 2.0352e-01, 1.9526e-01, 7.9145e-01, 2.0738e-01,
        9.9683e-01, 4.2802e-01, 5.2487e-02, 8.0118e-01, 3.9467e-01, 3.4634e-01,
        1.0511e-01, 9.5215e-01, 7.8968e-

## Pytorch and NumPy

* default dtype when converting from numpy array to tensor is float64

In [62]:
import torch
import numpy

array = numpy.arange(0.0, 10.0)
print(f"array = {array}")
tensor = torch.from_numpy(array)
print(f"tensor = {tensor}")
tensor_f32 = torch.from_numpy(array).type(torch.float32)
print(f"tensor_f32 = {tensor_f32}")
numpy_tensor = tensor_f32.numpy()
print(f"numpy_tensor = {numpy_tensor}")

array = [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
tensor = tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)
tensor_f32 = tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
numpy_tensor = [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## Reproducibility
To increase reproducibility random seed is used

In [63]:
torch.rand(3), torch.rand(3), torch.rand(3), torch.rand(3)


(tensor([0.8823, 0.6990, 0.6192]),
 tensor([0.4137, 0.0534, 0.8001]),
 tensor([0.7998, 0.0751, 0.6847]),
 tensor([0.6603, 0.3539, 0.8063]))

In [64]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
MATRIX1 = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
MATRIX2 = torch.rand(3, 4)
MATRIX1 == MATRIX2

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Using a GPU

In [65]:
 # Checking GPU
 !nvidia-smi

Tue Oct 15 10:22:28 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.02              Driver Version: 560.94         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3080 Ti     On  |   00000000:01:00.0  On |                  N/A |
|  0%   49C    P8             31W /  350W |     335MiB /  12288MiB |      8%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [66]:
# Checking access with pytorch
torch.cuda.is_available()

True

# Device Agnostic code

In [67]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [68]:
# Count number of devices
torch.cuda.device_count()

1

## Putting tensors (and models) on a GPU
(NumPy works only on cpu)

In [69]:
# Create a tensor (default on the CPU)
tensor = torch.rand(2, 2)
tensor.device

device(type='cpu')

In [70]:
# Moving tensor to GPU (if aviable)
tensor = tensor.to(device)
tensor.device

device(type='cuda', index=0)

In [71]:
# tensor.numpy() #TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
numpy_array = tensor.cpu().numpy()
numpy_array

array([[0.86940444, 0.5677153 ],
       [0.74109405, 0.4294045 ]], dtype=float32)

In [72]:
# back to GPU
tensor = torch.from_numpy(numpy_array).to(device)
tensor

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]], device='cuda:0')